name: Deploy mdBook

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**' # Only run when docs change

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Install mdBook
      - name: Install mdBook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.36/mdbook-v0.4.36-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv mdbook /usr/local/bin/

      # 2. Build the Site
      # We explicitly use the directory path so we don't need to 'cd' manually
      - name: Build Site
        run: mdbook build docs

      # 3. Deploy
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/book # mdBook outputs here by default
